### ISSUE TITLE
.gitignore accounted for or not?

### ISSUE THREAD

**Issue by ZerGo0** [jw0k/gwatch#2]
Hey,

quick question, does this take .gitignore into account or does it see the file change and tries to commit it even tho the file/folder is ignored?

**Comment by jw0k** [comment]
Hi,

Looks like .gitignore is not handled correctly. It will create empty commits when .gitignore is present and there are some ignored files. Thanks for mentioning that. I'll fix it once I have some free time.

**Comment by jw0k** [comment]
@ZerGo0 The bug has been fixed in v0.2. Files from .gitignore should be correctly ignored now.
